module.exports = [
  '♥ It was attraction when we met, but now love is going to keep us together forever! 🥰',
  '♥ My life has fell into place since the day you became mine, I love you so much! 🥰',
  '♥ You taught me true meaning of life from you sweetheart. Thanks for being there for me always! 🥰',
  '♥ You are there when I go to sleep, you are there when I wake up, and most importantly, you are there when I need you the most. I can not do nothing without thinking of you! 😘',
  '♥ I miss your smile, your gentle touch, your loving care. I just can’t wait to be with you again! 😘',
  '♥ No matter how high, I would climb a thousand mountains, no matter the amount of miles, I would walk them, no matter the ocean, I would swim across it, no matter what type of surface, I would crawl a thousand yards, all to see your smile. 😘',
  '♥ If you see a shooting star, make a wish. You may just end up with a true love’s first kiss. 😘',
  '♥ With you in my life, the world seems much happier, the birds chirp a little louder, the sun shines just a little brighter, the grass grows a bit greener, and my heart beats a little faster. 😘',
  'Dear LOML, If I was allowed to own a drop of water to show you how much I loved you, then l would be the owner of the Mississippi. 😘',
  'Baby, seeing you smile brightens my days. On my darkest days, all I crave is your smile and your electric touch. In so many ways, you heal every broken part in me.😘',
  'You gave me light in the dark, water in times of thirst, joy in my saddest moments. All I want is for you to be happy forever. Let me make you the happiest woman on the planet. 😘',
  'If an Angel asked me to make a wish, I would ask for a greater length of days because I want to show you how much you mean to me every day. 😘',
  '♥ Our hands fit so tightly together, as if they were made for each other. 😘',
  '♥ My love for you skyrockets with every moment we spend with each other; every touch, every kiss, and every word just pushes my love further up.  😘',
  '♥ You do not understand how necessary it is for me to hear your voice every day. I want so much to just hold you, and wake up beside of you, and just be there with you to love you. 😘',
  '♥ You are my shining star on a cloudy night, you are my rainbow on a stormy day, you are my blooming flower over the misting rain, and most important, you are my sun when I need you to brighten my day. I love you. 😘',
  '😍 Saying that you’re beautiful doesn’t express how gorgeous you actually are. Every time I see you, my heart skips a beat. 😘',
  'I’ve never cuddled with an angel before, but I’ve lost my teddy bear, and I need you to come cuddle with me. 😘',
  'I love all of your body, but your smile is something that I could never do without in my life. 😘',
  'I have been searching for someone like you my entire life, and nothing compares to the love and kindness that I found in you. 😍',
  '🥰 You are breathtaking today, I can’t wait to see the happiness radiate off of you when we see each other today. 🥰',
  '🥰 You and I belong together; I want you to always read my texts and smile just because they are from me. 🥰',
  '🥰 The signals that you send must be strong because whenever I walk by you, I feel a strong connection that draws me even closer. 🥰',
  '♥ I wish everyday could be like today, beautiful and sweet, just like you girl! 🥰',
  '♥ I tried to stop thinking about you, but it is just not earthly possible. I love you and every inch of your perfect body. 🥰',
  '♥ You are the reason I wake up with a smile on my face every morning. You are never off my mind; You are in my dreams, and even then, you are still perfect in every way. 🥰',
  '♥ I could say to you a thousand words on how much I really love you, and how absolutely wonderful you are, but still then it would not be enough. 🥰',
  '🥰 When you smile, you light up my entire world. I hope the neighbors can sleep tonight.🥰',
];
